language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y cmake libXxf86vm-dev libxml2
    - curl http://www.rust-lang.org/rustup.sh | sudo -E sh
    - rustc -v
    - cargo -V
install:
    - sudo apt-get install libXxf8vm-dev
script:
    - cargo build --verbose
    - ls ./target/deps
    - ! ./target/deps/dummy
